### ISSUE TITLE
Callback was already called error

### ISSUE THREAD

**Issue by sahar922** [lwd-technology/react-app-rewire-define-plugin#2]
Hi,
After installing and trying to use the plugin, I've got compilation errors.

`throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (/Users/.../node_modules/neo-async/async.js:14:11)
    at /Users/.../node_modules/neo-async/async.js:2813:7
    at process._tickCallback (internal/process/next_tick.js:61:11)
`

any suggestions?

**Comment by tlehwalder** [comment]
same for me

**Comment by zhaofang** [comment]
how to fix it?

**Comment by kopax** [comment]
same here

**Comment by kopax** [comment]
A test package has been released:

```bash
$ npm install @yeutech-lab/react-app-rewire-define-plugin --save-dev
```

In your code:

```js
const rewireDefinePlugin = require('@yeutech-lab/react-app-rewire-define-plugin');

    // Use `webpack.DefinePlugin` to add the version number from package.json
    config = rewireDefinePlugin(config, env, {
      'process.env.VERSION': JSON.stringify(require('./package.json').version),
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
      'process.env.GA_TRACKING_ID': JSON.stringify(process.env.GA_TRACKING_ID),
    });
```

Waiting PR to be merge
